import api, { publicApi } from '@/lib/api';

export interface StorefrontSettings {
  delivery_fee: number;
  free_delivery_threshold: number;
  store_enabled: boolean;
  announcement?: string;
  min_order_amount?: number;
  tax_rate?: number;
  tax_name?: string;
  custom_domain?: string;
  delivery_estimate?: string;       // e.g. "3 – 5 business days"
  location_suggestions?: string[];  // e.g. ["Accra", "Kumasi"]
  phone_placeholder?: string;       // e.g. "+233 XX XXX XXXX"
  // How the shop looks. Empty means the GEMS navy, which is what every
  // storefront was before a shop could choose.
  brand_color?: string;
  banner_image?: string;
  tagline?: string;
  hero_headline?: string;
  /** Lives on the tenant, not in storefront_settings — see the controller. */
  logo?: string;
}

// ── Shared TypeScript interfaces ────────────────────────────────────────────
/** One question a customer answers: "Size", and the values on offer. */
export interface ProductOption {
  name: string;
  values: { value: string; in_stock: boolean }[];
}

/** One buyable combination — a navy medium — with its own price and count. */
export interface ProductVariant {
  /** Canonical identity, generated by the server. Never built on the client. */
  key: string;
  selections: { name: string; value: string }[];
  price: number;
  available: number;
  sku?: string;
}

export interface StoreProduct {
  id: string;
  name: string;
  /** The product's public address. Absent until the backfill has run. */
  slug?: string;
  price: number;
  // cost_price is deliberately absent: the public catalogue endpoint used to
  // send it — what the shop paid, for every item — and nothing ever showed it.
  compare_price?: number;
  /**
   * The name of the promotion that produced the reduced price, when one did.
   *
   * Set by the server as it applies promotions, so a card can say "Easter Sale"
   * where it would otherwise say "Save 25%". The shop's own words beat a
   * calculated percentage.
   */
  promotion_name?: string;
  /**
   * What the customer must choose before they can order, and which values are
   * still available. Absent or empty for the great majority of products, which
   * come one way.
   */
  options?: ProductOption[];
  /** Every combination that can be bought, with its own price and count. */
  variants?: ProductVariant[];
  description?: string;
  sku?: string;
  images: string[];
  stock_qty: number;
  low_stock_threshold: number;
  category_name?: string;
  branch_id?: string;
  branch_name?: string;
  branch_slug?: string;
  is_active: boolean;
  item_type?: 'product' | 'service' | 'bundle';
  unit_type?: string;
  duration?: number;
  /** All stored since the catalogue was built, and shown for the first time. */
  unit?: string;
  attributes?: Record<string, unknown>;
  /** Resolved against the category server-side: real labels, chosen order. */
  specs?: { label?: string; value?: string }[];
  short_description?: string;
  brand?: string;
  highlights?: string[];
  bundle_items?: { name?: string; quantity?: number }[];
  requires_file?: boolean;
  service_type?: string;
}

export interface StoreTenant {
  id: string;
  business_name: string;
  slug: string;
  logo?: string;
  email?: string;
  phone?: string;
  address?: string;
}

export interface StoreBranch {
  id: string;
  name: string;
  slug: string;
  address?: string;
}

export interface StoreCustomer {
  id: string;
  name: string;
  email: string;
  phone?: string;
}

export interface StoreOrder {
  id: string;
  _id?: string;
  order_number: string;
  status: string;
  payment_status: string;
  total: number;
  createdAt?: string;
  created_at?: string;
  items?: Array<{ product_name: string; quantity: number; unit_price: number }>;
  delivery_address?: string;
}

/**
 * What the shop front says when the owner has written nothing.
 *
 * It advertises rather than merely stating a fact, because most shops will
 * never open the settings page and this line is what their customers read. It
 * promises only things GEMS actually does: the whole range is browsable, the
 * order takes a moment, and payment goes through Paystack by card or mobile
 * money. Nothing here mentions delivery, which is not true of a shop selling
 * services.
 *
 * Defined once. It was written out separately in the storefront and in the
 * settings preview, which is a drift waiting to happen — the preview is
 * supposed to be the promise that the shop front will look like this.
 */
export const DEFAULT_HERO_MESSAGE =
  'Browse everything we have, order in a few taps, and pay securely by card or mobile money.';

/**
 * Whether a stock figure means anything for this item.
 *
 * The storefront has always asked `stock_qty > 0` of anything that was not a
 * service, and a bundle is neither. A bundle holds no stock of its own — it is
 * available while the things inside it are, and the catalogue says so: stock
 * on the model is documented as ignored for services and bundles alike. So the
 * shop front read every bundle as sold out, refused to put one in a cart, and
 * hid it behind the "in stock only" filter. Nothing had ever been a bundle
 * before now, which is why nobody had seen it.
 */
export function tracksStock(item: { item_type?: string }): boolean {
  return item.item_type !== 'service' && item.item_type !== 'bundle';
}

/** Whether a customer can buy this right now. */
export function isAvailable(item: { item_type?: string; stock_qty?: number }): boolean {
  return !tracksStock(item) || (item.stock_qty ?? 0) > 0;
}

export const DEFAULT_STOREFRONT_SETTINGS: StorefrontSettings = {
  delivery_fee: 30,
  free_delivery_threshold: 500,
  store_enabled: true,
  announcement: '',
  min_order_amount: 0,
  delivery_estimate: '3 – 5 business days',
  location_suggestions: [],
  phone_placeholder: '',
};

export function normalizeStorefrontSettings(raw: Partial<StorefrontSettings> | null | undefined): StorefrontSettings {
  return {
    delivery_fee: Number(raw?.delivery_fee ?? DEFAULT_STOREFRONT_SETTINGS.delivery_fee),
    free_delivery_threshold: Number(raw?.free_delivery_threshold ?? DEFAULT_STOREFRONT_SETTINGS.free_delivery_threshold),
    store_enabled: raw?.store_enabled ?? DEFAULT_STOREFRONT_SETTINGS.store_enabled,
    announcement: raw?.announcement ?? '',
    min_order_amount: Number(raw?.min_order_amount ?? 0),
    tax_rate: Number(raw?.tax_rate ?? 0),
    tax_name: raw?.tax_name ?? '',
    custom_domain: String(raw?.custom_domain ?? '').toLowerCase().trim(),
    delivery_estimate: raw?.delivery_estimate ?? DEFAULT_STOREFRONT_SETTINGS.delivery_estimate,
    location_suggestions: Array.isArray(raw?.location_suggestions) ? raw.location_suggestions : [],
    phone_placeholder: raw?.phone_placeholder ?? '',
    // This function rebuilds the object field by field, so anything not named
    // here is dropped on the way in — which is silent, and looks exactly like a
    // shop's colour never having saved.
    brand_color: String(raw?.brand_color ?? '').trim().toLowerCase(),
    banner_image: String(raw?.banner_image ?? '').trim(),
    tagline: String(raw?.tagline ?? '').trim(),
    hero_headline: String(raw?.hero_headline ?? '').trim(),
    logo: String(raw?.logo ?? '').trim(),
  };
}

export function calcTaxAmount(subtotal: number, taxRatePct = 0): number {
  if (!subtotal || !taxRatePct) return 0;
  return Math.round(subtotal * taxRatePct / 100);
}

export function calcDeliveryFee(subtotal: number, settings: StorefrontSettings): number {
  if (subtotal <= 0) return 0;
  return subtotal >= settings.free_delivery_threshold ? 0 : settings.delivery_fee;
}

export function amountUntilFreeDelivery(subtotal: number, settings: StorefrontSettings): number {
  if (subtotal >= settings.free_delivery_threshold) return 0;
  return Math.max(0, settings.free_delivery_threshold - subtotal);
}

/** Public settings for a tenant storefront (no auth). */
export async function fetchPublicStoreSettings(tenantSlug: string): Promise<StorefrontSettings> {
  try {
    const r = await publicApi.get(`/storefront/${tenantSlug}/settings`);
    return normalizeStorefrontSettings(r.data.data);
  } catch {
    return { ...DEFAULT_STOREFRONT_SETTINGS };
  }
}

/** Merchant settings (authenticated). */
export async function fetchMerchantStoreSettings(): Promise<StorefrontSettings> {
  try {
    const r = await api.get('/storefront/settings');
    return normalizeStorefrontSettings(r.data.data);
  } catch {
    return { ...DEFAULT_STOREFRONT_SETTINGS };
  }
}

export async function saveMerchantStoreSettings(settings: StorefrontSettings): Promise<StorefrontSettings> {
  const r = await api.put('/storefront/settings', settings);
  return normalizeStorefrontSettings(r.data.data);
}

/** Public order lookup for customers. */
export async function trackStoreOrder(tenantSlug: string, reference: string) {
  const r = await publicApi.get(
    `/storefront/${tenantSlug}/orders/${encodeURIComponent(reference.trim())}`,
  );
  return r.data.data;
}
